### ISSUE TITLE
Error: Could not find a storyboard named 'DatePickerPopover' in bundle NSBundle 

### ISSUE THREAD

**Issue by DesmondPang** [hsylife/SwiftyPickerPopover#10]
It could not find the storyboard file.

` Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'DatePickerPopover' in bundle NSBundle `

**Comment by ktorimaru** [comment]
It is on Github
https://github.com/hsylife/SwiftyPickerPopover/blob/master/SwiftyPickerPopover/StringPickerPopoverViewController.swift

How did you install?

Ken

**Comment by hsylife** [comment]
Hello, @DesmondPang ,
Sorry. When I installed it via CocoaPods, I faced to the same issue.
Some Storyboard files were forgotten to bundle. 
I will fix it.

Yuta

**Comment by hsylife** [comment]
It has been fixed. 
Thank you, @DesmondPang and @ktorimaru!

Yuta

**Comment by aiyub007** [comment]
not yet fixed I still can't find the classes

**Comment by hsylife** [comment]
Hello @aiyub007,
Did you face to the same error message mentioned by @DesmondPang ?

**Comment by hsylife** [comment]
Hey guys,
I published another repository to grab a clue.
https://github.com/hsylife/TestSwiftyPickerPopover
I recognize that this projects on the repository are currently working.

**Comment by Jevon718** [comment]
Could it have anything to do with the version.  When I install its 1.1.0 but I notice you say to use 1.1.0.rc.2.  I type       pod ‘SwiftyPickerPopover’, ‘~> 1.1.0.rc.2’   in my pod file but it looks like it still installs 1.1.0.  Is my syntax right?

**Comment by hsylife** [comment]
Thanks @Jevon718,
Did you face to the issue when you want to install SwiftyPickerPopover 1.1.0 written in Swift2.3?

Then, I have to tell you 2 points.

One is that SwiftyPickerPopover 1.1.0 still has a bug when installing it via CocoaPods. Please give a time to fix it.

The other is that the version number "1.1.0.rc.2" is for CocoaPods, NOT for SwiftyPickerPopover. So, when I must say, you should specify pod ‘SwiftyPickerPopover’, ‘~>1.1.0' into the podfile. However, because SwiftyPickerPopover 1.1.0 has a bug as I wrote, you cannot get successful by the steps.

Yuta

**Comment by hsylife** [comment]
I have fixed the issue as SwiftyPickerPopover 1.2.0 has pushed to the branch "1.2.0".
Now, you can install it via CocoaPods 1.1.0.rc.2 by specifying "pod 'SwiftyPickerPopover '~> 1.2.0'" into your podfile.

Yuta

**Comment by starhoshi** [comment]
I encountered the same issue...
I'm using Swift3 and cocoapods@1.1.0.rc.2.

**Comment by hsylife** [comment]
Hello @starhoshi,
Did you exactly face to the same error message?

Yuta

**Comment by starhoshi** [comment]
Yes, I face to the same error message. But sorry, my repository is private.

`Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Could not find a storyboard named 'DatePickerPopover' in bundle NSBundle `

---

I Think [SwiftyPickerPopover\.podspecr](https://github.com/hsylife/SwiftyPickerPopover/blob/master/SwiftyPickerPopover.podspec)'s source_files is not include `storyboard`.

When I looked Installed Pods Directory, exist only .swift files.

```
Project/Pods/SwiftyPickerPopover/SwiftyPickerPopover$ ls -al
total 80
drwxr-xr-x  11 kensuke  staff   374 10 14 16:11 .
drwxr-xr-x   5 kensuke  staff   170 10 14 16:11 ..
-r--r--r--   1 kensuke  staff  1663 10 14 16:11 AbstractPopover.swift
-r--r--r--   1 kensuke  staff  5578 10 14 16:11 ColumnStringPickerPopover.swift
-r--r--r--   1 kensuke  staff  2268 10 14 16:11 ColumnStringPickerPopoverViewController.swift
-r--r--r--   1 kensuke  staff  2603 10 14 16:11 CountdownPickerPopover.swift
-r--r--r--   1 kensuke  staff  2276 10 14 16:11 CountdownPickerPopoverViewController.swift
-r--r--r--   1 kensuke  staff  2592 10 14 16:11 DatePickerPopover.swift
-r--r--r--   1 kensuke  staff  1661 10 14 16:11 DatePickerPopoverViewController.swift
-r--r--r--   1 kensuke  staff  3102 10 14 16:11 StringPickerPopover.swift
-r--r--r--   1 kensuke  staff  1607 10 14 16:11 StringPickerPopoverViewController.swift
```

**Comment by hsylife** [comment]
@starhoshi ,thanks for sharing error message.
As you told me, I have to fix the podspec file. 
I'm working on the issue.

**Comment by hsylife** [comment]
@starhoshi, It's done. 

Yuta

**Comment by hsylife** [comment]
Hey guys, The fixed version is pushed as SwiftyPickerPopover 1.2.1 for Swift 2.3.

Yuta
