### ISSUE TITLE
Use images in Picker

### ISSUE THREAD

**Issue by mrsnax** [hsylife/SwiftyPickerPopover#42]
Hi, 

I'm use SwiftyPickerPopover, but I want the text change into my Assets images, how to do that? thank you

**Comment by hsylife** [comment]
Hello, @mrsnax 
We need to create a new subclass of pickerPopover from AbstractPopover for appearing images by using pickerView(_:viewForRow:forComponent:reusing:) instead of pickerView(_:titleForRow:forComponent:). of  StringPicker.

Would you like to appear an image instead of a text, but not with a text?

**Comment by mrsnax** [comment]
I need to show images and text or vice versa

**Comment by hsylife** [comment]
How about layout? I'm thinking something like UITableViewCell layout.

**Comment by mrsnax** [comment]
yes you're correct ! its like UITableViewCell layout, how to creating like that? any examples code?

**Comment by hsylife** [comment]
OK. We need to create a new subclass as I said.
I should add the code into this project as soon as possible.

**Comment by mrsnax** [comment]
thank you for the replies
I will try, if any problems, I will post again

**Comment by mrsnax** [comment]
HI,
I tried the code using below : 
`p.pickerView(pick, viewForRow: 1, forComponent: 1, reusing: images.image)`

But i've got error. Please advices

**Comment by hsylife** [comment]
Hi, @mrsnax 
I've released the new version, which has be able to have images like a UITableViewCell.
Please try it.
