### ISSUE TITLE
Force date format programatically  

### ISSUE THREAD

**Issue by dipeshparashar** [hsylife/SwiftyPickerPopover#56]
Is it possible to force different date format programatically.
I want to set it to **Day-Month-Year**

**Comment by hsylife** [comment]
@dipeshparashar 
Basically, It's possible.

At first, since DatePickerPopover uses a UIDatePicker, we cannot change the date picker format directly.

However, in certain cases, you can use this property to change the format. For example, if you can assume that the user only uses English, you can change the format from "MM-dd-YYYY" to "dd-MM- YYYY" by changing the locale from "en-US" to "en-GB".  

The latest version, SwiftyPickerPopover 5.2.0, has been added setLocale(). You can read how to use this the demo project.

Secondly, If you want to change the format essentially, you can implement it based on ColumnStringPickerPopover. It needs to prepare calendar processing by yourself. An API to set the action to be taken if a row is selected may need to be implemented. Like "setActionAfterRowSelected()".

By the way, I think that a picker date format should be base on the user setting for user experience.
